plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\益养宣推广 - trae\\jiayue-website"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]